# -*- coding: utf-8 -*-
"""division.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19b2k6SpkZn3fK5z6Q2m5kHR2hVvPMeKV
"""

try:
    number_1 = float(input("Введите делимое: "))
    number_2 = float(input("Введите делитель: "))
    division = number_1 / number_2
    print(division)
    print(f"Результат: {number_1} / {number_2} = {division}")
except ZeroDivisionError:
    print("Ошибка: на ноль делить нельзя!")
except ValueError:
    print("Ошибка: введите корректное число!")